# Используем Nginx для раздачи статики
FROM nginx:alpine

# Копируем собранные файлы из фронтенд-контейнера в директорию Nginx
COPY --from=frontend:latest /app/dist /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]